service: nodejs-aws-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: prod

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
